# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('guest', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('attend', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
