# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170113_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='attend',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(blank=True, default='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest',
            field=models.CharField(default='Guest Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='message',
            field=models.CharField(blank=True, default='Send up a message', max_length=100),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
